### ISSUE TITLE
Trouble with alt + right-key

### ISSUE THREAD

**Issue by rsodhia-clover** [softmoth/zsh-vim-mode#10]
First, awesome plugin. I'm new to zsh, and this seems great. Unfortunately, I'm running into trouble using alt + right key; it doesn't work. I can do left to go back a word, and del work now, but can't go forward a word.

If it matters, I'm on OSX 10.13.4 and using iTerm.

**Comment by softmoth** [comment]
This should be working. Can you please run `cat -v`, and then type Alt+Left and Alt+Right to see what they produce? You might be able to add the appropriate escape sequence to the line `vim-mode-define-special-key Alt-Left ...`. Let me know what you find out! Thank you for the report.
