### ISSUE TITLE
^R does not work once a search term has been found

### ISSUE THREAD

**Issue by lrworth** [softmoth/zsh-vim-mode#12]
In standard `bindkey -v` mode it is possible to:
* press ^R
* enter a search term
* repeatedly press ^R to find further occurrences of the search term.

This does not work with zsh-vim-mode. Is an alternative provided?

**Comment by softmoth** [comment]
This does work for me (it's essential behavior, I agree!). Can you please let me know the ZSH version, and strip down your .zshrc to a minimal test case that shows the problem? Thank you!

**Comment by lrworth** [comment]
Sorry @softmoth somehow I missed the message in Feb. I can't reproduce this either — I think it was interacting with something else which I've since removed.
