### ISSUE TITLE
The surround text object does not work.

### ISSUE THREAD

**Issue by jdhao** [softmoth/zsh-vim-mode#13]
Thanks for your great work! I have used this plugin and it works quite well. 

I have found that the surround object does not work as expected. Specifically, `ds`, `cs`, `ys` do not seem to work. When I am in NORMAL mode, press `s` after either `d`, `c` or `y` will change the editing mode to INSERT mode. `S` in the VISUAL MODE work as expected.

+ My system: CentOS 7
+ zsh version: 5.6.2

I am using the latest version of this plugin installed via zplug. Let me know if you need any further information.

**Comment by softmoth** [comment]
Hi, thank you for this report, and I'm very glad you enjoy this plugin.

If you *disable* zsh-vim-mode, and just use the settings shown at the top of the [source file](https://sourceforge.net/p/zsh/code/ci/master/tree/Functions/Zle/surround) for the Zle/surround function, does it work as you want it to?

If so, then it's a bug in zsh-vim-mode somehow. This would help me to ensure I am looking in the right place to understand the problem.

Thanks!

**Comment by jdhao** [comment]
If I only use the following setting in `.zshrc` (backing up the original `.zshrc`):

```zshrc
bindkey -v
autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
```

I can use `cs`, `ds` and `ys` and `S` in visual mode.  But it seems that `ys` only work for text object `iw`, `aw` but not for other text objects. 

But if I comment out the part about `zsh-vim-mode` and add the above setting in my original `.zshrc`, none of the `cs`, `ds` and `ys` works (only `S` work in visual mode). 

Maybe it has something to do with other plugins I install?

**Comment by jdhao** [comment]
I think I have found the plugin which interfere with the surround mode.  If I disable the plugin [`zsh-autosuggestions`](https://github.com/zsh-users/zsh-autosuggestions), then `zsh-vim-mode` can work.

Steps to reproduce:

+ Use the following setting in `.zshrc` (I use zplug to manage plugins):
```
source ~/.zplug/init.zsh

zplug "softmoth/zsh-vim-mode"
# zplug "zsh-users/zsh-autosuggestions"

zplug load --verbose
```
Now surround object works properly.

+ Un-comment the line about autosuggestions and login again. Surround does not work anymore.

**Comment by jdhao** [comment]
After some more search, I found [this issue](https://github.com/zsh-users/zsh-autosuggestions/issues/254) on the zsh-autosuggestion repo. It suggests to set variable `KEYTIMEOUT` to be above 25 in `.zshrc`.

After that, it seems surround objects can work without any noticeable issues.

**Comment by softmoth** [comment]
Great, thanks for tracking that down! It seems like a good trade-off; it's *barely* noticeable and I'd much rather have the correct behavior. I appreciate your help.
