### ISSUE TITLE
Put cursor at the end of the line

### ISSUE THREAD

**Issue by IKA3RUS** [softmoth/zsh-vim-mode#14]
My cursor is positioned at the start of the line instead of the end of the line when I press the up or down key. I found that the plugin changes the default bindings of the up and down keys to do a history substring search.

https://github.com/softmoth/zsh-vim-mode/blob/d0a53168fb448894b7a33befa30e489ef77c81d2/zsh-vim-mode.plugin.zsh#L179-L182

Can you make the cursor go to the end after pressing up or down? If that's not possible, can you add an option to get back the default behavior of the up and down keys?

**Comment by IKA3RUS** [comment]
Also, this doesn't happen when the [zsh-history-substring-search plugin](https://github.com/zsh-users/zsh-history-substring-search) is loaded.

https://github.com/softmoth/zsh-vim-mode/blob/d0a53168fb448894b7a33befa30e489ef77c81d2/zsh-vim-mode.plugin.zsh#L173-L177

So, this part of the code is working fine and the cursor is placed at the end appropriately.

**Comment by softmoth** [comment]
Thanks for the bug report. I had missed this before now. Yes, it should be possible to get the cursor to the end of the line. Or else restore the default binding, and rely on history-substring-search for added functionality.

**Comment by softmoth** [comment]
I've fixed this by restoring the default binding. As you said, the zsh-history-substring-search plugin is a good alternative for people who want a fancier Up-arrow experience.

Fixed in 1fd2124 .
