### ISSUE TITLE
[Feature Request] Options used to disable cursor styling, mode in prompt

### ISSUE THREAD

**Issue by laggardkernel** [softmoth/zsh-vim-mode#15]
The mode indicator in prompt has already been provided by many prompts, like powerlevel9k, spaceship-prompt. Frameworks like oh-my-zsh, prezto also have this feature included. Handling the job to prompts themselves seems to be more compatible. Can we have a switch to disable the "mode in prompt" feature of this plugin?

Besides, either cursor styling or vi mode in prompt is adequate to server as a indicator. It not very efficient to enable these widgets as the same time.

**Comment by softmoth** [comment]
If you set `MODE_INDICATOR=` before loading this plugin, then the prompt [is not touched](https://github.com/softmoth/zsh-vim-mode/blob/63749d145a04114aae5b15a583d736e337c5f7db/zsh-vim-mode.plugin.zsh#L408). That is, assuming you don't set any other `MODE_INDICATOR_*` variables.

If you do not set any `MODE_CURSOR_*` variables, the terminal escape sequence to change the cursor [is not sent](https://github.com/softmoth/zsh-vim-mode/blob/63749d145a04114aae5b15a583d736e337c5f7db/zsh-vim-mode.plugin.zsh#L544).

So you can have either one of those indicators, or both, or none, set individually for all modes.

No other framework tracks mode as well as this plugin. Use $VIM_MODE_KEYMAP from your theme or other plugins to use this plugin's logic without redundant indicators.
