### ISSUE TITLE
[Feature Request] Set default mode for each new prompt

### ISSUE THREAD

**Issue by squ94wk** [softmoth/zsh-vim-mode#17]
I found that when I use previous commands a lot and wanna change them slightly, I more often use normal mode to navigate than I use insert mode.

So I'd love an option to change the default mode ZLE is in on a new prompt.

A lot of attempts changing to mode outside of the plugin failed in various ways.

Hence, I changed line 295 in zsh-vim-mode.plugin.zsh to:
`vim_mode_set_keymap vicmd`
I'm not sure if it's the only place that effects this behaviour, but for now it works.

Could we have an option like `VIM_MODE_DEFAULT_MODE` or `VIM_MODE_INITIAL_MODE`?
One could also remember the last mode used, instead of resetting it every time. Then it would feel more like using vim as an editor.

**Comment by softmoth** [comment]
I like this idea. It might work, and should be straightforward to try.

**Comment by softmoth** [comment]
This was a bit more work than I expected, but I think I got it working. Let me know how it goes for you.
