### ISSUE TITLE
Breaks history suggestions starting with a string

### ISSUE THREAD

**Issue by gerazov** [softmoth/zsh-vim-mode#25]
Great plugin :+1: It seems not to work well with autosuggestions though. Might be related to #8 but even ordering the plugins as suggested doesn't make it right.

These are two issues I have:
- [x] going word by word in the suggestion can be done using `w` in normal mode (although it flashes some annoying output), but going back using `b` doesn't deselect them.
![zsh_vim_autocomplete](https://user-images.githubusercontent.com/15214418/84243426-776ae580-ab02-11ea-836a-ad0903047008.gif)

- [x] if I start typing a command and try cycling through the autosuggestions using `k` it deletes what I typed and cycles through all commands.
![zsh_vim_backintime](https://user-images.githubusercontent.com/15214418/84243625-c44ebc00-ab02-11ea-9228-8a4afdda6d4d.gif)

My plugin list reads:
```
plugins=(
  git
  extract
  colored-man-pages
  zsh-interactive-cd
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-vim-mode
  )
source $ZSH/oh-my-zsh.sh

VIM_MODE_ESC_PREFIXED_WANTED='bdfhul.g'  # Default is 'bdf.g'
```

**Comment by softmoth** [comment]
Thanks. I'll need to do some testing to see what specifically is conflicting, and probably look into how zsh-autosuggestions is implemented. Patches are welcome if anyone figures it out before I get to it!

**Comment by gerazov** [comment]
This might be due to the way that `zsh` handles vim mode as it also happens when I set `bindkey -v` so I opened an issue there https://github.com/zsh-users/zsh-autosuggestions/issues/545

**Comment by gerazov** [comment]
In the related issue there was an answer by @meav that fixes the scrolling through the history using beginning search. I'm adding it here too - https://github.com/zsh-users/zsh-autosuggestions/issues/545#issuecomment-736315918
> > To reproduce just start typing a command in insert mode and then switch to vim mode and try scrolling for different autosuggestions and it simply scrolls from history ignoring the typed text. This also doesn't work when scrolling back with arrow keys in insert mode.
> > ![zsh_vim_backintime](https://user-images.githubusercontent.com/15214418/84243625-c44ebc00-ab02-11ea-9228-8a4afdda6d4d.gif)
> 
> This is not a bug, I solved this by add more key bindding in .zshrc:
> 
> ```
> bindkey -M vicmd "k" up-line-or-beginning-search
> bindkey -M vicmd "j" down-line-or-beginning-search
> ```

**Comment by gerazov** [comment]
I find that the first issue is a colouring quirk - up/down search works with the words up to the cursor even though those you backtrack through stay the same colour :+1:

**Comment by softmoth** [comment]
Thank you, Branislav. I've added these keybindings if the respective ZLE widgets are defined. Hopefully that makes it Just Work for everyone.
