### ISSUE TITLE
after install; does not enter vi mode

### ISSUE THREAD

**Issue by sktrinh12** [softmoth/zsh-vim-mode#29]
hi i git cloned this repo into oh-my-zsh/plugin/ directory and restarted terminal. when i press Esc or Ctl+[ i cannt enter vi mode. how does this plugin work?

**Comment by softmoth** [comment]
Yes, either of those keys should just work. It sounds like you may need to add something to your oh-my-zsh config, perhaps adding `zsh-vim-mode` to the `plugins` array.

**Comment by softmoth** [comment]
Did that help? Do you still have questions about the plugin?

**Comment by sktrinh12** [comment]
Hi, sorry for late reply. I got it somewhat working by moving the line of code around in my .zshrc file (trial and error). I did have that plugin line of code prior to but still had issues. It works now, but my prompt doesnt show up properly. I just havent bothered to try to fix that. I prefer the vim bindings to work

**Comment by softmoth** [comment]
Okay. I don't use oh-my-zsh, but I hope you can find some help in their forums. Let me know if you find a problem with this plugin, or some installation help that should be added to the docs here. Thanks!
