### ISSUE TITLE
zle's history-search functionality is not working

### ISSUE THREAD

**Issue by Ramkumar47** [softmoth/zsh-vim-mode#30]
Hi developer!
It is a great tool, i like it very much. The only issue i face is that the **zle's history-search** doesnot work when this plugin is enabled. 
http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#History-Control

by history-search i mean this example..
in command suppose i type "vim" and press up arrow key, zsh will go back to the command that started with vim without considering what the last command was. But with this plugin enabled, zsh goes back to the immediate last command irrespective of the line typed in the buffer.. 

is this really an issue or am i missing something in my configs?

**Comment by Ramkumar47** [comment]
i think you may take a look at this post https://superuser.com/questions/1357131/zsh-in-vi-mode-but-using-arrow-keys-to-search-history, which shows my problem and the solution to it.. 
i would like you to include those in the plugin.

also please modify/add feature that the text copied using "yank" commands like "y$" Y" etc... will be copied to the clipboard so that the copied text can be pasted to other places

**Comment by softmoth** [comment]
Hi, I used to have this in, and it caused complaints so I took it out. I will think of how to add a configuration option for it.

**Comment by Ramkumar47** [comment]
ok, thank you for considering this.. have a nice day!

**Comment by bitdivision** [comment]
This would be fantastic, I can't really use this plugin until this works

Is there any way to allow it through changing bindings?

Edit: it looks as though the code in the superuser post does work for this plugin too :)

**Comment by softmoth** [comment]
Thank you again for filing this issue. I've finally added [the history-search-end bindings](https://github.com/zsh-users/zsh/blob/master/Functions/Zle/history-search-end) by default. I believe they will be safe, after reviewing the previous problems (issue #14).
