### ISSUE TITLE
Allow `%` to work with string quotes

### ISSUE THREAD

**Issue by HaleTom** [softmoth/zsh-vim-mode#34]
I found myself writing:

```
cd "$(dirname "$(realpath "${@:$#}")")-backup"
```

To check that my quotes were right, I tried pressing <kbd>%</kbd> multiple times with my cursor over a `"` character.
 
Expected behaviour: Cursor bounces between matching `"` characters
Actual behaviour: Cursor bounces over `(` and `)` characters

**Comment by softmoth** [comment]
Hi! This is a good suggestion. I think it belongs in ZSH itself, since the `%` key is handled entirely by the built-in `vi-match-bracket` widget. The zsh-workers mailing list is where feature discussions take place for ZSH: https://www.zsh.org/mla/
