### ISSUE TITLE
Existing Esc bindings get blocked even with VIM_MODE_VICMD_KEY set

### ISSUE THREAD

**Issue by FallenWarrior2k** [softmoth/zsh-vim-mode#37]
I'm an avid user of [fzf's key bindings](https://github.com/junegunn/fzf#key-bindings-for-command-line), mainly Alt-C (i.e. `^[c`) for fuzzy `cd`, and I've noticed that if I load fzf's bindings before zsh-vim-mode, the Alt-C binding doesn't work even if I've explicitly set `VIM_MODE_VICMD_KEY` to something that doesn't include Esc. Pressing Esc once also puts me into normal mode as if the custom key wasn't set at all, except the custom key does the same.
All other fzf bindings still work though, so I'm assuming they didn't somehow end up in the wrong keymap at least.

Minimal `.zshrc`:
```
source "/usr/share/fzf/key-bindings.zsh"

VIM_MODE_VICMD_KEY='^B'
source "~/path/to/repos/softmoth/zsh-vim-mode/zsh-vim-mode.plugin.zsh"
```

Moving the fzf line to the end expectedly restores functionality, but imo that shouldn't be necessary if I've already told zsh-vim-mode that it shouldn't use Esc.

Of course, I am aware that, at its core, zsh-vim-mode is a wrapper around Zsh functionality, so if this a limitation of Zsh itself, feel free to close this as an upstream bug (? or whatever it is).

**Comment by softmoth** [comment]
I believe it is in the core functionality of `bindkey -v`. There is no explicit binding of Esc in `zsh-vim-mode`. And `VIM_MODE_VICMD_KEY` does not unbind Esc, it just adds another key to use for the `vi-cmd-mode` widget and frees up a few more Emacs-like bindings.

Thanks for posting this bug report. Feel free to re-open if you find some preferable workaround or have further questions.
