### ISSUE TITLE
Cursor is hidden in the first prompt with Powerlevel10k

### ISSUE THREAD

**Issue by alitajelsir** [softmoth/zsh-vim-mode#38]
- The cursor is hidden in the first prompt when used with Powerlevel10k. It only appears if the mode is changed (to normal then insert) or in the next prompt after entering a command).

- Screenshots:
![Screenshot_20210302_091113](https://user-images.githubusercontent.com/26362874/109615176-44f39380-7b3c-11eb-8607-ff8ada897ef8.png)
![Screenshot_20210302_094618](https://user-images.githubusercontent.com/26362874/109615178-4624c080-7b3c-11eb-9128-bdc0ec6f72d3.png)

- Atached are my zshrc and powerlevel10k configuration files:
[zshrc.txt](https://github.com/softmoth/zsh-vim-mode/files/6066777/zshrc.txt)
[p10k.zsh.txt](https://github.com/softmoth/zsh-vim-mode/files/6066781/p10k.zsh.txt)

- Update:
Disabling instant prompt of powerlevel10k solved the issue, but it was compatible before. Also tried [jeffreytse/zsh-vi-mode](https://github.com/jeffreytse), and it's working fine.

**Comment by softmoth** [comment]
Hi, sorry I didn't notice this sooner. I'll try to reproduce this problem. Thank you for letting me know!

**Comment by softmoth** [comment]
Hi, I just pushed a fix for this. It was a weird one, and I'm not sure why it happens in powerlevel10k, but I removed the event that was triggering it from zsh-vim-mode, so hopefully it's a better citizen in the ZLE widget hook community.

Thanks for reporting the problem!

**Comment by alitajelsir** [comment]
- Tried the latest commit just now, and it's working fine.
- Thanks for your hard work 😁!.
