### ISSUE TITLE
Bug: pasting in normal mode seems to cut out characters

### ISSUE THREAD

**Issue by Tycholiz** [softmoth/zsh-vim-mode#44]
I've been able to reproduce this on 2 different machines.

### Recreate
1. copy the following `npx ts-node ./scripts/runIntegrationTest.ts`
2. paste it into your terminal, making sure that you are in normal mode (pasting in insert mode seems to work fine)
3. check to see if the correct paste came off your clipboard. 
    - on my computer, the word "integration" is misspelled "interation"

**Comment by softmoth** [comment]
Hi, thank you for the bug report, and for trying out the plugin!

This is unrelated to zsh-vim-mode, it's a bug in `bracketed-paste-magic`. I can reproduce it with just:

```zsh
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
```

Bracketed paste magic is not enabled by zsh-vim-mode, I suspect it's done separately in your zshrc.
