### ISSUE TITLE
Konsole: pressing Enter appends a 'q' to the command, visual effect only

### ISSUE THREAD

**Issue by lashoun** [softmoth/zsh-vim-mode#6]
On Konsole 18.04.3, enabling zsh-vim-mode appends a 'q' character to the command when pressing Enter.
The effect is only visual but it's quite disturbing.
Disabling zsh-vim-mode solves the issue. The issue does not appear on xfce4-terminal.

EDIT: not sure if it's relevant to mention it here but the plugin is great.

**Comment by softmoth** [comment]
I confirm I can reproduce this. I'll see what I can find out.

**Comment by softmoth** [comment]
Looks to be addressed in a recent (2018-04-19) patch to Konsole. I'll need some more time to address it and maybe implement a workaround for older Konsole (and iTerm also?). If anyone can send a patch / pull request that makes Konsole / iTerm work, that'd be appreciated.

Relevant Konsole bug report: https://bugs.kde.org/show_bug.cgi?id=347323

The KONSOLE_VERSION variable isn't exported yet in 18.04.3, so it's not clear how to adjust behavior based on version. I'd need to do some reading to sort out what Konsole needs. I think for right now I might just disable cursor styling if KONSOLE_PROFILE_NAME is set.

**Comment by softmoth** [comment]
Thanks for this report, and I'm glad you like the plugin! Feel free to reopen it if the present solution isn't what you'd hoped for.
