### ISSUE TITLE
Error while sourcing - add-zle-hook-widget

### ISSUE THREAD

**Issue by qaraluch** [softmoth/zsh-vim-mode#7]
System: Win10 + WSL
zsh: 5.1.1 (x86_64-ubuntu-linux-gnu)

When sourcing plugin I get:
```
(anon):1: add-zle-hook-widget: function definition file not found
/home/qyadr/.antigen/bundles/softmoth/zsh-vim-mode/zsh-vim-mode.plugin.zsh:558: add-zle-hook-widget: function definition file not found
```
This is the line:
```zsh
add-zle-hook-widget line-finish vim-mode-cursor-finish-hook
```
What is it for? 
Thanks.

**Comment by softmoth** [comment]
It's used to track the input mode (insert, command, search, etc.) and update the prompt / cursor style appropriately. The function is available since ZSH 5.3. http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Manipulating-Hook-Functions

**Comment by softmoth** [comment]
I should say that it would be possible to degrade functionality gracefully if that feature isn't present, and only track viins / vicmd modes (ignoring search and visual modes).

**Comment by qaraluch** [comment]
I need upgrade ZSH then. Thank you for help.
