### ISSUE TITLE
conflict with  zsh-autosuggestions & zsh-syntax-highlighting

### ISSUE THREAD

**Issue by commiyou** [softmoth/zsh-vim-mode#8]

**Comment by softmoth** [comment]
Thanks for this bug report! I am not familiar zsh-autosuggestions, but it appears to work OK for me. I tried a .zshrc with just:

```
source ~/g/zsh-vim-mode/zsh-vim-mode.plugin.zsh
source ~/Downloads/zsh-autosuggestions.zsh
```

And it seems to work as expected:

![Simple test screenshot](https://user-images.githubusercontent.com/774788/45573325-7ae81480-b829-11e8-85a2-98c245ec1d6a.png)

Can you please try the latest ZSH version and a simple test .zshrc? And then gradually add back things to your .zshrc until you can identify what causes the problem?

Then please describe the conflict you are getting, exact error message or exact behavior. Please include a screenshot if it would be illuminating.

**Comment by commiyou** [comment]
![image](https://user-images.githubusercontent.com/5888756/46180925-b1c42d00-c2f5-11e8-8109-09f9a8f8dfa2.png)

**Comment by CallumHoward** [comment]
Hi, I'm also seeing this with similar configuration to @commiyou. From the screenshot I can deduce @commiyou is using [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) to load plugins (so am I).

I have only observed a conflict with zsh-autosuggestions so far. 

My .zshrc (with oh-my-zsh installed) is:
```zsh
plugins=(zsh-vim-mode zsh-syntax-highlighting zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
```
After reading [this](
https://github.com/zsh-users/zsh-autosuggestions/issues/6#issuecomment-282572841) I was inclined to put `zsh-autosuggestions` after `zsh-syntax-highlighting`, but I don't think it should affect anything.

My repro is:
- type a command with multiple words
- after the first word and spacebar is pressed, autosuggestion remains but dark grey highlighting reverts to default color (white)

I also discovered a workaround, it seems this autosuggestion highlighting issue doesn't happen if I load `zsh-vim-mode` after the other two plugins like:
```zsh
plugins=(zsh-syntax-highlighting zsh-autosuggestions zsh-vim-mode)
```

**Comment by CallumHoward** [comment]
I have also noticed that the highlighting on `history-search-multi-word` [plugin](https://github.com/zdharma/history-search-multi-word) is now gone as well.

**Comment by gzrjzcx** [comment]
same as me
how to solve these conflicts?

**Comment by softmoth** [comment]
I'm sorry for the long delay on fixing this. It looks like it is a conflict between the newish (zsh 5.3) `add-zle-hook-widget` that I'm using, vs. the old method of modifying `${widgets}` directly. I've narrowed it down to the line `add-zle-hook-widget line-pre-redraw vim-mode-line-pre-redraw`. If that's removed, the conflicts go away (and all of vim-mode's tracking of the input mode is gone, of course).

But even setting that hook to `vim-mode-line-pre-redraw  () { true }` causes the problem. So it's not the content of the hook, but its existence, that causes the problem. The funny thing is, neither zsh-autosuggestions nor zsh-syntax-highlighting mention redraw at all. So I have some more digging to do to find out how to work around this.

If you don't care about zsh-vim-mode's `MODE_CURSOR_*` or `MODE_INDICATOR_*` features, then commenting out `line-pre-redraw` [here](https://github.com/softmoth/zsh-vim-mode/blob/68f601bdc8c28dd656882214db87a2a861bb6125/zsh-vim-mode.plugin.zsh#L233) is a quick workaround for now.

**Comment by softmoth** [comment]
I should mention that ordering the plugins like this seems to work fully:
```
export ZSH=~/.oh-my-zsh
plugins=(
    history-search-multi-word
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-vim-mode
)
source $ZSH/oh-my-zsh.sh
bindkey "^R" history-search-multi-word
```

**Comment by laggardkernel** [comment]
I got the same requirement of loading sequence as above after trial and error. But when I enable another plugin adding `line-finish` widget (before `syntax-highlighting`) with `add-zle-hook-widget`, the shell close at once after I press `Enter`. It seems that both `zsh-syntax-highlighting` and `fast-syntax-highlighting` have problem dealing with the `add-zle-hook-widget` method.

I guess we need to make sure all widgets enabled by `add-zle-hook-widget` should be added after `syntax-highlighting`?

**Comment by CallumHoward** [comment]
Seems to be all resolved for me! Thanks.
