### ISSUE TITLE
Garbage characters with fbterm

### ISSUE THREAD

**Issue by HaleTom** [softmoth/zsh-vim-mode#9]
I use [`fbterm`](https://github.com/izmntuk/fbterm) on my linux console.  It only supports 256 colours due to the kernel's console 8-bit limitation.

For my general use, I have the configuration:

```
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_VIINS="#20d08a blinking bar"
MODE_CURSOR_SEARCH="#ff00ff steady underline"
```

When my shell loads, I see:

```
ravi@svelte:~% 2;#20d08aq12q
ravi@svelte:~% 12q
ravi@svelte:~% 12q
```

Every time I press enter I get `12q` appended.

I suspect that there is a terminfo lookup missing somewhere, or a test that if the terminal doesn't support truecolour, then don't try to output those codes.

**Comment by softmoth** [comment]
The `MODE_CURSOR_*` code only works with XTerm-compatible terminals. I'm open to supporting other terms, it would just mean modifying `set-terminal-cursor-style`. Add a test for the alternate term in an `if`, and leave the existing code as the `else`. Don't worry about making it too pretty, if we only support two styles then no need to get fancy.

Basically, I want to ensure that if you don't explicitly set those variables, then you won't get garbage on your terminal. If you do set them, then you need to be using a supported term. So either you can use an `if` in your zshrc to only set them when your term supports the XTerm sequences, or else modify `set-terminal-cursor-style` to do what fbterm needs.

Ideally a robust query of the terminal properties would enable doing this automatically, but I think this would require using some external dependency like [xtermcontrol](https://github.com/JessThrysoee/xtermcontrol), and I don't see a clean way of enabling features even if that dependency isn't available. I haven't thought of a good solution yet.

**Comment by softmoth** [comment]
I looked into this a little bit. Fbterm isn't being developed anymore, but there is a fork that handles XTerm escapes and should allow cursor styling to work.

https://github.com/lheckemann/fbterm/commits/master

**Comment by HaleTom** [comment]
Thanks a bunch for your dedication and attention to detail with this plugin.

I'll check out that repo now.  Cheers!
